name: Update Python Poetry packages

on:
  schedule:
    - cron: '0 5 * * *' # every day at 5:00 am
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
        - uses: fuzzylabs/gha-poetry-update@v1
          with:
            python-version: '3.12.11'
            poetry-version: '2.1.1'
