name: "Evaluation tests"
run-name: "Evaluation tests"

on:
  pull_request_target:
    types: [labeled, opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - ".reuse/**"
      - "LICENSES/**"
      - "config/**"
      - "data/**"
      - "docs/**"
      - "scripts/**"
      - "tests/**"
      - "**/*.md"
      - "doc_indexer/**"
      - CODEOWNERS
      - LICENSE

jobs:
  evaluation:
    uses: kyma-project/kyma-companion/.github/workflows/evaluation-test-reusable.yaml@main
