name: Update Python Poetry packages

on:
  schedule:
    - cron: '0 5 * * *' # Every day at 5:00 am.
  workflow_dispatch: # Allows manually triggering the workflow.

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
        - uses: friedrichwilken/update-poetry-dependencies@add_workflow_reference
          with:
            python-version: '3.12.11'
            poetry-version: '2.1.1'
            pr-title-prefix: 'deps: '
            pr-labels: 'help wanted,bug'
            test-command: "echo '{\"mock-key\": \"mock-value\"}' > config/config.json && poetry run poe pre-commit-check"
            github_token: ${{ secrets.github_token }}
