name: Update Python Poetry packages

on:
  schedule:
    - cron: '0 5 * * *' # every day at 5:00 am
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
        - uses: friedrichwilken/gha-poetry-update@main
          with:
            python-version: '3.12.11'
            poetry-version: '2.1.1'          
            pr-title-prefix: 'deps:'
            pr-labels: 'enhancement'
            test-command: poetry run poe pre-commit-change
